In [25]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt  # for plots
import pdb
from sklearn.linear_model import RidgeCV

In [26]:

from sklearn import linear_model

X=[[1.,1.],[2.,2.],[1.,5.],[7.,8.]]
y=[2.,4.,6.,15.]

X=np.asarray(X).reshape((4, 2))
y=np.asarray(y).reshape((4, 1))


#X = preprocessing.scale(X)

# Create linear regression object
regr = linear_model.LinearRegression(fit_intercept=False)

# Train the model using the training sets
regr.fit(X, y)
regr.coef_

array([[ 1.,  1.]])

In [27]:
#Least Squares

from sklearn import preprocessing
import pdb
import numpy as np
from numpy import linalg as LA

theta = np.random.randn(2, 1)   # initialize theta vector

theta=[10.,15.]
theta=np.asarray(theta)
theta = theta[:,np.newaxis]

#X = np.random.randn(9, 6)
#y = np.random.randn(9, 1)
#x = np.array([1,2,3], dtype=np.int64)
X=[[1.,1.],[2.,2.],[1.,5.],[7.,8.]]
y=[2.,4.,6.,15.]

X=np.asarray(X).reshape((4, 2))
y=np.asarray(y).reshape((4, 1))


def OLS_coordinate_descent(X,y,theta,epoch,tolerance):
    
    r = y - np.dot(X,theta)
    for m in range(0,epoch):
        for j in range(0,len(theta)):
            theta_old = 100.
            theta_new = theta[j,0]
            Xt = X[:,j][:,np.newaxis]
            #pdb.set_trace()
            #for k in range(0,100):
            while (LA.norm(theta_new-theta_old)  > tolerance):
                theta_old = theta_new
                r_int = r+ Xt * theta_old
                theta_new = (np.dot(X[:,j],r_int) / LA.norm(X[:,j])**2)[0]
                r = r_int - np.dot(Xt,theta_new)
                #print LA.norm(r)

            theta[j,0] = theta_new

    print theta

OLS_coordinate_descent(X,y,theta,50,0.01)

[[ 0.9962018 ]
 [ 1.00266682]]


In [28]:
#Ridge

from sklearn import preprocessing
import pdb
import numpy as np
from numpy import linalg as LA

theta = np.random.randn(2, 1)   # initialize theta vector
lamda = 1
theta=[8.,8.]
theta=np.asarray(theta)
theta = theta[:,np.newaxis]

#X = np.random.randn(9, 6)
#y = np.random.randn(9, 1)
#x = np.array([1,2,3], dtype=np.int64)
X=[[1.,1.],[2.,2.],[1.,5.],[7.,8.]]
y=[2.,4.,6.,15.]

X=np.asarray(X).reshape((4, 2))
y=np.asarray(y).reshape((4, 1))


def Ridge_coordinate_descent(X,y,theta,epoch,tolerance,lamda):
    
    r = y - np.dot(X,theta)
    for m in range(0,epoch):
        for j in range(0,len(theta)):
            theta_old = 100.
            theta_new = theta[j,0]
            Xt = X[:,j][:,np.newaxis]
            #pdb.set_trace()
            #for k in range(0,100):
            while (LA.norm(theta_new-theta_old)  > tolerance):
                theta_old = theta_new
                r_int = r+ Xt * theta_old
                theta_new = (np.dot(X[:,j],r_int) / (LA.norm(X[:,j])**2+lamda))[0]
                r = r_int - np.dot(Xt,theta_new)
                #print LA.norm(r)

            theta[j,0] = theta_new

    print theta

Ridge_coordinate_descent(X,y,theta,50,0.01,100)

[[ 0.50221669]
 [ 0.65388504]]


In [30]:
from sklearn import cross_validation
from sklearn.linear_model import Ridge
import scipy


X=[[1.,1.],[2.,2.],[1.,5.],[7.,8.]]
y=[2.,4.,6.,15.]

X=np.asarray(X).reshape((4, 2))
y=np.asarray(y).reshape((4, 1))


clf = Ridge(alpha=100)
clf.fit(X,y)
print clf.coef_

[[ 0.31356659  0.34693488]]


In [57]:
# Lasso

from sklearn import preprocessing
import pdb
import numpy as np
from numpy import linalg as LA

theta = np.random.randn(2, 1)   # initialize theta vector
lamda = 1
theta=[8.,8.]
theta=np.asarray(theta)
theta = theta[:,np.newaxis]

#X = np.random.randn(9, 6)
#y = np.random.randn(9, 1)
#x = np.array([1,2,3], dtype=np.int64)
X=[[1.,1.],[2.,2.],[1.,5.],[7.,8.]]
y=[2.,4.,6.,15.]

X=np.asarray(X).reshape((4, 2))
y=np.asarray(y).reshape((4, 1))


def soft_thresh(z,lamda):
    if abs(z)<= lamda:
        return 0
    if z >= lamda:
        return (z-lamda)
    if z <= lamda:
        return (z+lamda)
    
def Lasso_coordinate_descent(X,y,theta,epoch,tolerance,lamda):
    
    r = y - np.dot(X,theta)
    for m in range(0,epoch):
        for j in range(0,len(theta)):
            theta_old = 100.
            theta_new = theta[j,0]
            Xt = X[:,j][:,np.newaxis]
           
            while (LA.norm(theta_new-theta_old)  > tolerance):
                theta_old = theta_new
                r_int = r+ Xt * theta_old
                z = (np.dot(X[:,j],r_int) / (LA.norm(X[:,j])**2))[0]
                thresh = lamda/(LA.norm(X[:,j])**2)
                theta_new = soft_thresh(z,thresh)
                #theta_new = (np.dot(X[:,j],r_int) / (LA.norm(X[:,j])**2+lamda))[0]
                r = r_int - np.dot(Xt,theta_new)
                #print LA.norm(r)

            theta[j,0] = theta_new

    print theta

Lasso_coordinate_descent(X,y,theta,100,0.01,100)


[[ 0.        ]
 [ 0.63829787]]


In [45]:
from sklearn import preprocessing
import pdb
import numpy as np
from numpy import linalg as LA
from sklearn import linear_model

theta = np.random.randn(2, 1)   # initialize theta vector
lamda = 1
theta=[8.,8.]
theta=np.asarray(theta)
theta = theta[:,np.newaxis]

#X = np.random.randn(9, 6)
#y = np.random.randn(9, 1)
#x = np.array([1,2,3], dtype=np.int64)
X=[[1.,1.],[2.,2.],[1.,5.],[7.,8.]]
y=[2.,4.,6.,15.]

X=np.asarray(X).reshape((4, 2))
y=np.asarray(y).reshape((4, 1))



clf = linear_model.Lasso(alpha=1)
clf.fit(X,y)
print clf.coef_

[ 0.87637218  0.95732707]


In [32]:
# Cross Validation

from sklearn import cross_validation
from sklearn.linear_model import Ridge
import scipy

n_samples, n_features = 10, 5
np.random.seed(0)
y = np.random.randn(n_samples)
X = np.random.randn(n_samples, n_features)
errors =[]
kf = cross_validation.KFold(X.shape[0], n_folds=10)

Score_mat = np.empty([1,10])
Score_mat = scipy.delete(Score_mat,0,0)  # define S as an empty matrix
for i in range(1,6,1):
    
    clf = Ridge(alpha=i)
    scores = []
    for train_index, test_index in kf:
        #pdb.set_trace()
        X_train, X_test = X[train_index], X[test_index]
        y_train, y_test = y[train_index], y[test_index]
        clf.fit(X_train, y_train)
        y_hat = clf.predict(X_test)
        error = LA.norm((y_test-y_hat))
        errors.append(error)
    #Score_mat = np.vstack((Score_mat,scores))

print np.argmax(errors)

14
